name: Deploy Touran Live

on:
  push:
    branches: [ master ]
    paths:
      - 'touran-deploy/**'
      - '.github/workflows/deploy-touran.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - name: Install sshpass
        run: sudo apt-get update -qq && sudo apt-get install -y -qq sshpass
      - name: Create remote folder
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e ssh -p "${{ secrets.SFTP_PORT }}" -o StrictHostKeyChecking=no "${{ secrets.SSH_USERNAME }}@${{ secrets.SFTP_HOST }}" "mkdir -p ~/httpdocs/touran"
      - name: Upload Touran Live
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e scp -P "${{ secrets.SFTP_PORT }}" -o StrictHostKeyChecking=no -r touran-deploy/* "${{ secrets.SSH_USERNAME }}@${{ secrets.SFTP_HOST }}:~/httpdocs/touran/"
