/* 135er-Grow Central Future HUD v0.7 */
const $=id=>document.getElementById(id);
const diag=x=>$("diagnostics").textContent=typeof x==="string"?x:JSON.stringify(x,null,2);
function clock(){$("clock").textContent=new Date().toLocaleTimeString("de-DE")}setInterval(clock,1000);clock();
function openView(id){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===id));document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));window.dispatchEvent(new CustomEvent("gc:view",{detail:{id}}))}
document.querySelectorAll(".nav-item").forEach(btn=>btn.addEventListener("click",()=>openView(btn.dataset.view)));
document.querySelectorAll("[data-open-view]").forEach(btn=>btn.addEventListener("click",()=>openView(btn.dataset.openView)));
const slider=$("speedSlider");function updateRing(){const v=Number(slider.value);$("speedValue").textContent=v;const deg=v*3.6;$("ring").style.background=`conic-gradient(var(--green) ${deg}deg, rgba(53,240,167,.08) ${deg}deg)`}slider.addEventListener("input",updateRing);updateRing();
async function api(url,options={}){const r=await fetch(url,{cache:"no-store",...options});if(r.redirected&&new URL(r.url).pathname==="/login")throw new Error("Die GUI-Sitzung wurde beendet. Bitte mit den aktuellen Zugangsdaten neu anmelden.");let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||`${r.status} ${r.statusText}`);return data}
function writeToken(){let token=sessionStorage.getItem("gcLocalWriteToken")||"";if(!token){token=prompt("Lokales Grow Central Write-Token eingeben. Es wird nur für diese Browser-Sitzung gespeichert.")||"";if(token)sessionStorage.setItem("gcLocalWriteToken",token)}return token}
async function writeApi(url,options={},providedToken=""){const token=providedToken||writeToken();if(!token)throw new Error("Kein Write-Token angegeben");if(providedToken)sessionStorage.setItem("gcLocalWriteToken",providedToken);const headers=new Headers(options.headers||{});headers.set("X-API-Token",token);headers.set("Content-Type","application/json");return api(url,{...options,headers})}
const fmt=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):"--";
const kwh=v=>Number.isFinite(Number(v))?(Number(v)/1000).toFixed(3):"--";
function boolText(value){return value===true?"JA":value===false?"NEIN":"--"}
function detail(label,value){return `<div><span>${escapeHtml(label)}</span><strong>${escapeHtml(value??"--")}</strong></div>`}
const DEVICE_PREVIEWS=[
  {match:/fc[- _]?3000/i,src:"/static/device-images/mars-hydro-fc3000.webp",alt:"Mars Hydro FC3000"},
  {match:/df[- _]?150[- _]?m|ifresh|mz_mzf002/i,src:"/static/device-images/mars-hydro-df150-m.webp",alt:"Mars Hydro DF150-M / iFresh 6 Zoll"},
  {match:/logitech.*c920|c920.*logitech|\bc920\b/i,src:"/static/device-images/logitech-c920.webp",alt:"Logitech C920"},
  {match:/fritz!?(?:dect|smart energy)[- _]?210|(?:dect|smart energy)[- _]?210/i,src:"/static/device-images/fritz-dect-210.webp",alt:"FRITZ!DECT 210"},
];
function devicePreview(...values){const text=values.filter(Boolean).join(" ");const image=DEVICE_PREVIEWS.find(row=>row.match.test(text));return image?`<figure class="device-preview"><img src="${image.src}" alt="${escapeHtml(image.alt)}" loading="lazy"><figcaption>HERSTELLER-MODELLBILD</figcaption></figure>`:'<div class="device-preview device-preview-fallback" aria-label="Noch kein eindeutiges Modellbild"><span>?</span><small>MODELL NOCH NICHT EINDEUTIG</small></div>'}
function plugCard(row,compact=false){
  const s=row.state||{};const isFritz=row.adapter==="fritz";const isOn=s.on===true;
  const status=row.error?"ERROR":row.online?(isOn?"ON":"OFF"):"OFFLINE";const cls=row.online?(isOn?"on":"off"):"offline";
  const model=s.product_name||row.metadata?.product||row.adapter||"Smart Plug";
  const controls=!compact&&row.approved&&row.writable?`<button class="plug-switch ${isOn?"active":""}" data-plug="${escapeHtml(row.id)}" data-next="${!isOn}">${isOn?"AUSSCHALTEN":"EINSCHALTEN"}</button>`:"";
  const temperature=isFritz?`<div class="plug-temperature"><span>UMGEBUNG</span><strong>${fmt(s.temperature_c,1)} °C</strong><small>Offset ${fmt(s.temperature_offset_c,1)} °C</small></div>`:"";
  const fritzDetails=!compact&&isFritz?`<div class="plug-identity">
    ${detail("Modell",s.product_name)}${detail("FRITZ!-Name",s.native_name)}${detail("Hersteller",s.manufacturer)}${detail("AIN",s.ain)}
    ${detail("Firmware",s.firmware_version)}${detail("Interne Geräte-ID",s.device_id)}${detail("Schaltmodus",s.switch_mode)}${detail("Funktionsbitmaske",s.function_bitmask)}
    ${detail("UI-Schaltsperre",boolText(s.ui_lock))}${detail("Gerätesperre",boolText(s.device_lock))}${detail("Funkübertragung aktiv",boolText(s.tx_busy))}${detail("Batterie",s.battery_percent==null?"nicht vorhanden":`${fmt(s.battery_percent,0)} %`)}
  </div><div class="plug-functions"><span>GEMELDETE FUNKTIONEN</span><strong>${escapeHtml((s.functions||[]).join(" · ")||"Keine Funktionsklassen gemeldet")}</strong><small>Quelle: lokale FRITZ!Box AHA-Geräteinformation</small></div>`:"";
  return `<article class="plug-card ${cls} ${isFritz?"fritz-plug":""}">${!compact?devicePreview(model,s.manufacturer):""}<div class="plug-head"><div><span class="mini-label">${escapeHtml(model)}</span><strong>${escapeHtml(s.native_name||row.name||row.id)}</strong></div><span class="plug-state">${status}</span></div><div class="plug-live"><div class="plug-power"><b>${fmt(s.power_w)}</b><span>W</span></div>${temperature}</div><div class="plug-stats"><div><span>Energie gesamt</span><strong>${kwh(s.energy_wh)} kWh</strong></div><div><span>Spannung</span><strong>${fmt(s.voltage_v,1)} V</strong></div><div><span>Strom${s.current_source?" (berechnet)":""}</span><strong>${fmt(s.current_a,3)} A</strong></div><div><span>Schaltzustand</span><strong>${s.on===true?"EIN":s.on===false?"AUS":"--"}</strong></div></div>${fritzDetails}${row.error?`<div class="plug-error">${escapeHtml(row.error)}</div>`:""}${controls}</article>`
}
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
let currentPowerW=0;
function getEnergyPrice(){const v=Number($("energyPrice")?.value);return Number.isFinite(v)&&v>=0?v:0}
function updateProjection(){const kw=Math.max(0,currentPowerW)/1000;const price=getEnergyPrice();const periods={Hour:1,Day:24,Week:24*7,Month:24*30.4375,Year:24*365};for(const [name,hours] of Object.entries(periods)){const e=kw*hours;const c=e*price;$("proj"+name+"Kwh").textContent=e.toFixed(3);$("proj"+name+"Cost").textContent=c.toFixed(2)+" €"}}
const savedPrice=localStorage.getItem("gcEnergyPrice");if(savedPrice!==null&&$("energyPrice"))$("energyPrice").value=savedPrice;$("energyPrice")?.addEventListener("input",()=>{localStorage.setItem("gcEnergyPrice",$("energyPrice").value);updateProjection()});
async function refreshStatus(){try{const x=await api("/api/df100m/status");$("deviceListState").textContent=x.online?"ONLINE":"OFFLINE";$("deviceListState").style.color=x.online?"var(--green)":"var(--red)"}catch(e){diag("DF100M STATUS ERROR\n"+e.message)}}
let lastPlugSignature="";
async function refreshPower(){try{const x=await api("/api/v1/smarthome/overview");const s=x.summary||{};currentPowerW=Number(s.power_w)||0;$("totalPower").textContent=fmt(s.power_w);$("totalEnergy").textContent=kwh(s.energy_wh);$("plugOnline").textContent=`${s.online||0} / ${s.configured||0} online`;$("plugOnCount").textContent=s.switched_on||0;$("powerSummaryW").textContent=fmt(s.power_w);$("powerSummaryKwh").textContent=kwh(s.energy_wh);$("powerSummaryOnline").textContent=`${s.online||0} / ${s.configured||0}`;$("powerSummaryOn").textContent=s.switched_on||0;$("powerUpdated").textContent=new Date(x.timestamp).toLocaleTimeString("de-DE");$("powerDot").style.background=s.online>0?"var(--green)":"var(--red)";$("smartPlugState").textContent=x.enabled?`${s.online||0}/${s.configured||0} ONLINE`:"DISABLED";const rows=x.devices||[];const signature=JSON.stringify(rows);if(signature!==lastPlugSignature){lastPlugSignature=signature;$("plugGrid").innerHTML=rows.length?rows.map(r=>plugCard(r)).join(""):'<div class="empty-state">Keine Steckdosen konfiguriert.</div>';$("powerPreviewGrid").innerHTML=rows.length?rows.slice(0,3).map(r=>plugCard(r,true)).join(""):'<div class="empty-state">Keine Steckdosen konfiguriert.</div>';document.querySelectorAll("[data-plug]").forEach(btn=>btn.addEventListener("click",()=>switchPlug(btn.dataset.plug,btn.dataset.next==="true")))}updateProjection()}catch(e){$("smartPlugState").textContent="ERROR";diag("POWER TELEMETRY ERROR\n"+e.message)}}
async function switchPlug(id,on){if(!confirm(`${id} ${on?"einschalten":"ausschalten"}?`))return;try{diag(`Switching ${id} -> ${on?"ON":"OFF"}…`);const x=await writeApi(`/api/v1/smarthome/devices/${encodeURIComponent(id)}/switch`,{method:"POST",body:JSON.stringify({on})});diag(x);await refreshPower()}catch(e){diag("SMART PLUG WRITE ERROR\n"+e.message)}}
function candidateCard(row){return `<article class="candidate-card">${devicePreview(row.name,row.metadata?.model,row.metadata?.product,row.manufacturer)}<div class="candidate-head"><div><span class="provider-tag">${escapeHtml(row.provider)}</span><strong>${escapeHtml(row.name)}</strong><small>${escapeHtml(row.host)}${row.port?":"+row.port:""}</small></div><span class="candidate-source">${escapeHtml(row.metadata?.model||row.source||"")}</span></div><div class="button-row"><button class="secondary" data-probe-provider="${escapeHtml(row.provider)}" data-probe-host="${escapeHtml(row.host)}" data-probe-port="${row.port||""}">VERBINDUNG TESTEN</button><button class="ghost" data-register-provider="${escapeHtml(row.provider)}" data-register-host="${escapeHtml(row.host)}" data-register-name="${escapeHtml(row.name)}">ÜBERNEHMEN</button></div><pre class="probe-result" data-result-host="${escapeHtml(row.host)}">Noch nicht getestet.</pre></article>`}
function bluetoothCard(row){const candidate=row.classification==="df100m_candidate"||row.preferred;const label=candidate?"DF100M-KANDIDAT":(row.device_type||"BLUETOOTH-GERÄT");const details=[row.manufacturer,`RSSI ${row.rssi??"?"} dBm`].filter(Boolean).join(" · ");return `<article class="candidate-card">${devicePreview(row.display_name,row.name,row.manufacturer,row.device_type,candidate?"mz_mzf002":"")}<div class="candidate-head"><div><span class="provider-tag">${escapeHtml(label)}</span><strong>${escapeHtml(row.display_name||row.name||"Unbekanntes Bluetooth-Gerät")}</strong><small>MAC: ${escapeHtml(row.address)}</small></div><span class="candidate-source">${escapeHtml(details)}</span></div><div class="button-row"><button class="secondary" data-ble-address="${escapeHtml(row.address)}">VERBINDEN & GATT LESEN</button></div><pre class="probe-result" data-ble-result="${escapeHtml(row.address)}">${candidate?"Namenshinweis erkannt; Identität wird erst nach GATT-Prüfung bestätigt.":`${escapeHtml(row.device_type||"Bluetooth-Gerät")} anhand der ausgesendeten Geräteinformationen erkannt.`}</pre></article>`}
async function loadProviders(){try{const x=await api("/api/v1/smarthome/onboarding/providers");$("providerGrid").innerHTML=x.providers.map(p=>`<div class="provider-card"><strong>${escapeHtml(p.id).toUpperCase()}</strong><span>${p.control?"Steuerung bereit":escapeHtml(p.note||"Diagnose")}</span></div>`).join("")}catch(e){diag("PROVIDER ERROR\n"+e.message)}}
function bindCandidates(){document.querySelectorAll("[data-probe-provider]").forEach(btn=>btn.addEventListener("click",async()=>{const target=document.querySelector(`[data-result-host="${CSS.escape(btn.dataset.probeHost)}"]`);target.textContent="Teste Verbindung…";try{const x=await writeApi("/api/v1/smarthome/onboarding/probe",{method:"POST",body:JSON.stringify({provider:btn.dataset.probeProvider,host:btn.dataset.probeHost,port:btn.dataset.probePort?Number(btn.dataset.probePort):null})});target.textContent=JSON.stringify(x,null,2);diag(x)}catch(e){target.textContent=e.message}}));document.querySelectorAll("[data-register-provider]").forEach(btn=>btn.addEventListener("click",async()=>{const id=(prompt("Interne Geräte-ID (klein, ohne Leerzeichen)",`${btn.dataset.registerProvider}-${btn.dataset.registerHost.replaceAll(".","-")}`)||"").trim();if(!id)return;try{diag(await writeApi("/api/v1/smarthome/onboarding/register",{method:"POST",body:JSON.stringify({id,name:btn.dataset.registerName,provider:btn.dataset.registerProvider,host:btn.dataset.registerHost})}));await refreshPower()}catch(e){diag("REGISTER ERROR\n"+e.message)}}))}
async function scanSmartHome(){const button=$("smartScanBtn");button.disabled=true;$("scanStatus").textContent="Suche im lokalen Netz…";try{const x=await writeApi("/api/v1/smarthome/onboarding/discover?timeout=5",{method:"POST"});$("scanStatus").textContent=`${x.count} Gerät(e) gefunden.`;$("candidateGrid").innerHTML=x.devices.length?x.devices.map(candidateCard).join(""):'<div class="empty-state">Keine unterstützten Geräte gefunden. Sie müssen eingeschaltet und im selben LAN sein.</div>';bindCandidates();diag(x)}catch(e){$("scanStatus").textContent="Suche fehlgeschlagen: "+e.message;diag("LAN DISCOVERY ERROR\n"+e.message)}finally{button.disabled=false}}
$("smartScanBtn")?.addEventListener("click",scanSmartHome);loadProviders();
async function scanBluetooth(){const button=$("bleScanBtn");button.disabled=true;$("scanStatus").textContent="Bluetooth-Umgebung wird gescannt…";try{const x=await writeApi("/api/df100m/discover?timeout=8");$("scanStatus").textContent=`${x.devices?.length||0} Bluetooth-Gerät(e) gefunden.`;$("candidateGrid").innerHTML=x.devices?.length?x.devices.map(bluetoothCard).join(""):'<div class="empty-state">Keine BLE-Geräte gefunden.</div>';document.querySelectorAll("[data-ble-address]").forEach(btn=>btn.addEventListener("click",async()=>{const target=document.querySelector(`[data-ble-result="${CSS.escape(btn.dataset.bleAddress)}"]`);target.textContent="Verbinde…";try{const connected=await writeApi("/api/df100m/connect?address="+encodeURIComponent(btn.dataset.bleAddress),{method:"POST"});const services=await writeApi("/api/df100m/services");target.textContent=JSON.stringify({connected,services},null,2);diag({connected,services})}catch(e){target.textContent=e.message}}))}catch(e){$("scanStatus").textContent="Bluetooth-Suche fehlgeschlagen: "+e.message}finally{button.disabled=false}}
$("bleScanBtn")?.addEventListener("click",scanBluetooth);
$("tapoAccountForm")?.addEventListener("submit",async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;$("scanStatus").textContent="Tapo-Geräte werden auf allen aktiven Netzwerken gesucht…";try{const token=$("tapoApiToken").value.trim();const x=await writeApi("/api/v1/smarthome/onboarding/discover/account",{method:"POST",body:JSON.stringify({provider:"tapo",username:$("tapoUsername").value.trim(),password:$("tapoPassword").value,timeout:6})},token);$("scanStatus").textContent=`${x.count} Tapo/TP-Link-Gerät(e) in ${x.networks_scanned} Netzwerk(en) gefunden. Zugangsdaten gespeichert: nein.`;$("candidateGrid").innerHTML=x.devices.length?x.devices.map(candidateCard).join(""):'<div class="empty-state">Kein Tapo-Gerät gefunden. Gerät einschalten und dasselbe LAN/WLAN verwenden.</div>';bindCandidates();diag({count:x.count,credentials_stored:x.credentials_stored,networks_scanned:x.networks_scanned,devices:x.devices})}catch(e){$("scanStatus").textContent="Tapo-Suche fehlgeschlagen: "+e.message}finally{$("tapoPassword").value="";button.disabled=false}});
async function loadSystemDiagnostics(){const button=$("loadDiagnosticsBtn");button.disabled=true;$("systemDiagnostics").textContent="Lade Dienststatus und Journal…";try{$("systemDiagnostics").textContent=JSON.stringify(await writeApi("/api/v1/diagnostics/snapshot?lines=80"),null,2)}catch(e){$("systemDiagnostics").textContent="DIAGNOSEFEHLER\n"+e.message}finally{button.disabled=false}}
$("loadDiagnosticsBtn")?.addEventListener("click",loadSystemDiagnostics);
function setSetupMode(){const wifi=$("setupMode").value==="wifi";$("setupWifiFields").hidden=!wifi;$("setupSsid").required=wifi}
async function loadFirstBootStatus(){try{const state=await api("/api/setup/status");const panel=$("firstBootSetupPanel");panel.hidden=!state.setup_required;if(state.setup_required){openView("system");const messages=[state.error?`Letzter Fehler: ${state.error}`:"",state.warning?`Hinweis: ${state.warning}`:"",state.pending?"Konfiguration wird geprüft…":"Bitte Netzwerk und neue Zugangsdaten festlegen."].filter(Boolean);$("firstBootSetupStatus").textContent=messages.join(" ");const network=await api("/api/setup/network-status");if(!network.ethernet?.connected)$("setupMode").value="wifi";setSetupMode()}await refreshSupportBundleStatus()}catch(e){$("firstBootSetupStatus").textContent=e.message}}
async function scanSetupWifi(){const button=$("setupWifiScanBtn");button.disabled=true;$("setupWifiHint").textContent="WLAN-Suche läuft…";try{const data=await api("/api/setup/networks");$("setupWifiHint").textContent=data.message||`${data.networks.length} WLAN-Netz(e) gefunden.`;$("setupWifiList").innerHTML=data.networks.length?data.networks.map(row=>`<button class="ghost" type="button" data-setup-ssid="${escapeHtml(row.ssid)}">${escapeHtml(row.ssid)} · ${escapeHtml(row.signal)}% · ${escapeHtml(row.security||"offen")}</button>`).join(""):"";document.querySelectorAll("[data-setup-ssid]").forEach(item=>item.addEventListener("click",()=>{$("setupSsid").value=item.dataset.setupSsid}))}catch(e){$("setupWifiHint").textContent="WLAN-Suche fehlgeschlagen: "+e.message}finally{button.disabled=false}}
$("setupMode")?.addEventListener("change",setSetupMode);$("setupWifiScanBtn")?.addEventListener("click",scanSetupWifi);
$("firstBootSetupForm")?.addEventListener("submit",async event=>{event.preventDefault();const button=$("firstBootSubmitBtn");button.disabled=true;const data=Object.fromEntries(new FormData(event.currentTarget));data.fritz_enabled=false;$("firstBootSetupStatus").textContent="Konfiguration wird geprüft. Beim WLAN-Wechsel kann die Verbindung kurz abbrechen…";try{await api("/api/setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});$("firstBootSetupStatus").textContent="Übernommen. Der Pi prüft Netzwerk, Haupt-GUI und 135er-Grow-Central.local. Danach mit dem Heimnetz verbinden und die GUI erneut öffnen.";setTimeout(loadFirstBootStatus,5000)}catch(e){$("firstBootSetupStatus").textContent=e.message;button.disabled=false}});
$("restartSetupBtn")?.addEventListener("click",async()=>{if(!confirm("Setup wirklich erneut ausführen? Die bestehende Netzwerkverbindung bleibt bis zum Speichern aktiv."))return;try{await api("/api/setup/restart",{method:"POST"});await loadFirstBootStatus()}catch(e){$("supportBundleStatus").textContent=e.message}});
async function refreshSupportBundleStatus(){try{const state=await api("/api/v1/diagnostics/bundle/status");$("supportBundleStatus").textContent=state.pending?"Support-Datei wird erstellt…":state.available?`Support-Datei bereit (${Math.ceil(state.size/1024)} KiB). Bei Problemen immer diese Datei mitsenden.`:"Noch keine Support-Datei vorhanden.";$("downloadSupportBundleBtn").hidden=!state.available;return state}catch(e){$("supportBundleStatus").textContent=e.message;return null}}
$("createSupportBundleBtn")?.addEventListener("click",async()=>{const button=$("createSupportBundleBtn");button.disabled=true;try{await api("/api/v1/diagnostics/bundle",{method:"POST"});for(let i=0;i<60;i++){await new Promise(resolve=>setTimeout(resolve,2000));const state=await refreshSupportBundleStatus();if(state&&!state.pending)break}}catch(e){$("supportBundleStatus").textContent=e.message}finally{button.disabled=false}});
$("discoverBtn").addEventListener("click",async()=>{diag("Scanning BLE…");try{const x=await writeApi("/api/df100m/discover");diag(x);if(x.devices?.length){const d=x.devices[0];diag(await writeApi("/api/df100m/connect?address="+encodeURIComponent(d.address),{method:"POST"}));refreshStatus()}}catch(e){diag("DISCOVERY ERROR\n"+e.message)}});
$("servicesBtn").addEventListener("click",async()=>{diag("Reading GATT services…");try{diag(await writeApi("/api/df100m/services"))}catch(e){diag("GATT ERROR\n"+e.message)}});
$("sendSpeedBtn").addEventListener("click",async()=>{const v=Number(slider.value);if(!confirm(`Experimentellen DF100M-Testbefehl mit ${v}% senden?`))return;try{diag(await writeApi(`/api/df100m/speed?percent=${v}`,{method:"POST"}))}catch(e){diag("WRITE ERROR\n"+e.message)}});
let refreshRunning=false;
async function refreshAll(){if(refreshRunning||document.hidden)return;refreshRunning=true;try{await Promise.allSettled([refreshStatus(),refreshPower()])}finally{refreshRunning=false}}
$("refreshBtn").addEventListener("click",refreshAll);setInterval(refreshAll,15000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)refreshAll()});updateProjection();refreshAll();
loadFirstBootStatus();
