/* 135er-Grow Central Future HUD v0.7 */
const $=id=>document.getElementById(id);
const diag=x=>$("diagnostics").textContent=typeof x==="string"?x:JSON.stringify(x,null,2);
function clock(){$("clock").textContent=new Date().toLocaleTimeString("de-DE")}setInterval(clock,1000);clock();
function openView(id){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===id));document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id))}
document.querySelectorAll(".nav-item").forEach(btn=>btn.addEventListener("click",()=>openView(btn.dataset.view)));
document.querySelectorAll("[data-open-view]").forEach(btn=>btn.addEventListener("click",()=>openView(btn.dataset.openView)));
const slider=$("speedSlider");function updateRing(){const v=Number(slider.value);$("speedValue").textContent=v;const deg=v*3.6;$("ring").style.background=`conic-gradient(var(--green) ${deg}deg, rgba(53,240,167,.08) ${deg}deg)`}slider.addEventListener("input",updateRing);updateRing();
async function api(url,options={}){const r=await fetch(url,{cache:"no-store",...options});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||`${r.status} ${r.statusText}`);return data}
function writeToken(){let token=sessionStorage.getItem("gcLocalWriteToken")||"";if(!token){token=prompt("Lokales Grow Central Write-Token eingeben. Es wird nur für diese Browser-Sitzung gespeichert.")||"";if(token)sessionStorage.setItem("gcLocalWriteToken",token)}return token}
async function writeApi(url,options={}){const token=writeToken();if(!token)throw new Error("Kein Write-Token angegeben");const headers=new Headers(options.headers||{});headers.set("X-API-Token",token);headers.set("Content-Type","application/json");return api(url,{...options,headers})}
const fmt=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):"--";
const kwh=v=>Number.isFinite(Number(v))?(Number(v)/1000).toFixed(3):"--";
function plugCard(row,compact=false){const s=row.state||{};const isOn=s.on===true;const status=row.error?"ERROR":row.online?(isOn?"ON":"OFF"):"OFFLINE";const cls=row.online?(isOn?"on":"off"):"offline";const controls=!compact&&row.approved&&row.writable?`<button class="plug-switch ${isOn?"active":""}" data-plug="${escapeHtml(row.id)}" data-next="${!isOn}">${isOn?"AUSSCHALTEN":"EINSCHALTEN"}</button>`:"";return `<article class="plug-card ${cls}"><div class="plug-head"><div><span class="mini-label">${escapeHtml(row.adapter||"adapter")}</span><strong>${escapeHtml(row.name||row.id)}</strong></div><span class="plug-state">${status}</span></div><div class="plug-power"><b>${fmt(s.power_w)}</b><span>W</span></div><div class="plug-stats"><div><span>Energie</span><strong>${kwh(s.energy_wh)} kWh</strong></div><div><span>Spannung</span><strong>${fmt(s.voltage_v,0)} V</strong></div><div><span>Strom</span><strong>${fmt(s.current_a,2)} A</strong></div><div><span>Frequenz</span><strong>${fmt(s.frequency_hz,1)} Hz</strong></div></div>${row.error?`<div class="plug-error">${escapeHtml(row.error)}</div>`:""}${controls}</article>`}
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
let currentPowerW=0;
function getEnergyPrice(){const v=Number($("energyPrice")?.value);return Number.isFinite(v)&&v>=0?v:0}
function updateProjection(){const kw=Math.max(0,currentPowerW)/1000;const price=getEnergyPrice();const periods={Hour:1,Day:24,Week:24*7,Month:24*30.4375,Year:24*365};for(const [name,hours] of Object.entries(periods)){const e=kw*hours;const c=e*price;$("proj"+name+"Kwh").textContent=e.toFixed(3);$("proj"+name+"Cost").textContent=c.toFixed(2)+" €"}}
const savedPrice=localStorage.getItem("gcEnergyPrice");if(savedPrice!==null&&$("energyPrice"))$("energyPrice").value=savedPrice;$("energyPrice")?.addEventListener("input",()=>{localStorage.setItem("gcEnergyPrice",$("energyPrice").value);updateProjection()});
async function refreshStatus(){try{const x=await api("/api/df100m/status");$("deviceListState").textContent=x.online?"ONLINE":"OFFLINE";$("deviceListState").style.color=x.online?"var(--green)":"var(--red)"}catch(e){diag("DF100M STATUS ERROR\n"+e.message)}}
async function refreshPower(){try{const x=await api("/api/v1/smarthome/overview");const s=x.summary||{};currentPowerW=Number(s.power_w)||0;$("totalPower").textContent=fmt(s.power_w);$("totalEnergy").textContent=kwh(s.energy_wh);$("plugOnline").textContent=`${s.online||0} / ${s.configured||0} online`;$("plugOnCount").textContent=s.switched_on||0;$("powerSummaryW").textContent=fmt(s.power_w);$("powerSummaryKwh").textContent=kwh(s.energy_wh);$("powerSummaryOnline").textContent=`${s.online||0} / ${s.configured||0}`;$("powerSummaryOn").textContent=s.switched_on||0;$("powerUpdated").textContent=new Date(x.timestamp).toLocaleTimeString("de-DE");$("powerDot").style.background=s.online>0?"var(--green)":"var(--red)";$("smartPlugState").textContent=x.enabled?`${s.online||0}/${s.configured||0} ONLINE`:"DISABLED";const rows=x.devices||[];$("plugGrid").innerHTML=rows.length?rows.map(r=>plugCard(r)).join(""):'<div class="empty-state">Keine Steckdosen konfiguriert.</div>';$("powerPreviewGrid").innerHTML=rows.length?rows.slice(0,3).map(r=>plugCard(r,true)).join(""):'<div class="empty-state">Keine Steckdosen konfiguriert.</div>';document.querySelectorAll("[data-plug]").forEach(btn=>btn.addEventListener("click",()=>switchPlug(btn.dataset.plug,btn.dataset.next==="true")));updateProjection()}catch(e){$("smartPlugState").textContent="ERROR";diag("POWER TELEMETRY ERROR\n"+e.message)}}
async function switchPlug(id,on){if(!confirm(`${id} ${on?"einschalten":"ausschalten"}?`))return;try{diag(`Switching ${id} -> ${on?"ON":"OFF"}…`);const x=await writeApi(`/api/v1/smarthome/devices/${encodeURIComponent(id)}/switch`,{method:"POST",body:JSON.stringify({on})});diag(x);await refreshPower()}catch(e){diag("SMART PLUG WRITE ERROR\n"+e.message)}}
$("discoverBtn").addEventListener("click",async()=>{diag("Scanning BLE…");try{const x=await api("/api/df100m/discover");diag(x);if(x.devices?.length){const d=x.devices[0];diag(await api("/api/df100m/connect?address="+encodeURIComponent(d.address),{method:"POST"}));refreshStatus()}}catch(e){diag("DISCOVERY ERROR\n"+e.message)}});
$("servicesBtn").addEventListener("click",async()=>{diag("Reading GATT services…");try{diag(await api("/api/df100m/services"))}catch(e){diag("GATT ERROR\n"+e.message)}});
$("sendSpeedBtn").addEventListener("click",async()=>{const v=Number(slider.value);if(!confirm(`Experimentellen DF100M-Testbefehl mit ${v}% senden?`))return;try{diag(await writeApi(`/api/df100m/speed?percent=${v}`,{method:"POST"}))}catch(e){diag("WRITE ERROR\n"+e.message)}});
async function refreshAll(){await Promise.allSettled([refreshStatus(),refreshPower()])}
$("refreshBtn").addEventListener("click",refreshAll);setInterval(refreshAll,5000);updateProjection();refreshAll();
