/* 135er-Grow Central Future HUD v0.7 */
const $=id=>document.getElementById(id);
const diag=x=>$("diagnostics").textContent=typeof x==="string"?x:JSON.stringify(x,null,2);
function clock(){$("clock").textContent=new Date().toLocaleTimeString("de-DE")}setInterval(clock,1000);clock();
function openView(id){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===id));document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id))}
document.querySelectorAll(".nav-item").forEach(btn=>btn.addEventListener("click",()=>openView(btn.dataset.view)));
document.querySelectorAll("[data-open-view]").forEach(btn=>btn.addEventListener("click",()=>openView(btn.dataset.openView)));
const slider=$("speedSlider");function updateRing(){const v=Number(slider.value);$("speedValue").textContent=v;const deg=v*3.6;$("ring").style.background=`conic-gradient(var(--green) ${deg}deg, rgba(53,240,167,.08) ${deg}deg)`}slider.addEventListener("input",updateRing);updateRing();
async function api(url,options={}){const r=await fetch(url,{cache:"no-store",...options});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||`${r.status} ${r.statusText}`);return data}
function writeToken(){let token=sessionStorage.getItem("gcLocalWriteToken")||"";if(!token){token=prompt("Lokales Grow Central Write-Token eingeben. Es wird nur für diese Browser-Sitzung gespeichert.")||"";if(token)sessionStorage.setItem("gcLocalWriteToken",token)}return token}
async function writeApi(url,options={}){const token=writeToken();if(!token)throw new Error("Kein Write-Token angegeben");const headers=new Headers(options.headers||{});headers.set("X-API-Token",token);headers.set("Content-Type","application/json");return api(url,{...options,headers})}
const fmt=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):"--";
const kwh=v=>Number.isFinite(Number(v))?(Number(v)/1000).toFixed(3):"--";
function plugCard(row,compact=false){const s=row.state||{};const isOn=s.on===true;const status=row.error?"ERROR":row.online?(isOn?"ON":"OFF"):"OFFLINE";const cls=row.online?(isOn?"on":"off"):"offline";const controls=!compact&&row.approved&&row.writable?`<button class="plug-switch ${isOn?"active":""}" data-plug="${escapeHtml(row.id)}" data-next="${!isOn}">${isOn?"AUSSCHALTEN":"EINSCHALTEN"}</button>`:"";return `<article class="plug-card ${cls}"><div class="plug-head"><div><span class="mini-label">${escapeHtml(row.adapter||"adapter")}</span><strong>${escapeHtml(row.name||row.id)}</strong></div><span class="plug-state">${status}</span></div><div class="plug-power"><b>${fmt(s.power_w)}</b><span>W</span></div><div class="plug-stats"><div><span>Energie</span><strong>${kwh(s.energy_wh)} kWh</strong></div><div><span>Spannung</span><strong>${fmt(s.voltage_v,0)} V</strong></div><div><span>Strom</span><strong>${fmt(s.current_a,2)} A</strong></div><div><span>Frequenz</span><strong>${fmt(s.frequency_hz,1)} Hz</strong></div></div>${row.error?`<div class="plug-error">${escapeHtml(row.error)}</div>`:""}${controls}</article>`}
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
let currentPowerW=0;
function getEnergyPrice(){const v=Number($("energyPrice")?.value);return Number.isFinite(v)&&v>=0?v:0}
function updateProjection(){const kw=Math.max(0,currentPowerW)/1000;const price=getEnergyPrice();const periods={Hour:1,Day:24,Week:24*7,Month:24*30.4375,Year:24*365};for(const [name,hours] of Object.entries(periods)){const e=kw*hours;const c=e*price;$("proj"+name+"Kwh").textContent=e.toFixed(3);$("proj"+name+"Cost").textContent=c.toFixed(2)+" €"}}
const savedPrice=localStorage.getItem("gcEnergyPrice");if(savedPrice!==null&&$("energyPrice"))$("energyPrice").value=savedPrice;$("energyPrice")?.addEventListener("input",()=>{localStorage.setItem("gcEnergyPrice",$("energyPrice").value);updateProjection()});
async function refreshStatus(){try{const x=await api("/api/df100m/status");$("deviceListState").textContent=x.online?"ONLINE":"OFFLINE";$("deviceListState").style.color=x.online?"var(--green)":"var(--red)"}catch(e){diag("DF100M STATUS ERROR\n"+e.message)}}
async function refreshPower(){try{const x=await api("/api/v1/smarthome/overview");const s=x.summary||{};currentPowerW=Number(s.power_w)||0;$("totalPower").textContent=fmt(s.power_w);$("totalEnergy").textContent=kwh(s.energy_wh);$("plugOnline").textContent=`${s.online||0} / ${s.configured||0} online`;$("plugOnCount").textContent=s.switched_on||0;$("powerSummaryW").textContent=fmt(s.power_w);$("powerSummaryKwh").textContent=kwh(s.energy_wh);$("powerSummaryOnline").textContent=`${s.online||0} / ${s.configured||0}`;$("powerSummaryOn").textContent=s.switched_on||0;$("powerUpdated").textContent=new Date(x.timestamp).toLocaleTimeString("de-DE");$("powerDot").style.background=s.online>0?"var(--green)":"var(--red)";$("smartPlugState").textContent=x.enabled?`${s.online||0}/${s.configured||0} ONLINE`:"DISABLED";const rows=x.devices||[];$("plugGrid").innerHTML=rows.length?rows.map(r=>plugCard(r)).join(""):'<div class="empty-state">Keine Steckdosen konfiguriert.</div>';$("powerPreviewGrid").innerHTML=rows.length?rows.slice(0,3).map(r=>plugCard(r,true)).join(""):'<div class="empty-state">Keine Steckdosen konfiguriert.</div>';document.querySelectorAll("[data-plug]").forEach(btn=>btn.addEventListener("click",()=>switchPlug(btn.dataset.plug,btn.dataset.next==="true")));updateProjection()}catch(e){$("smartPlugState").textContent="ERROR";diag("POWER TELEMETRY ERROR\n"+e.message)}}
async function switchPlug(id,on){if(!confirm(`${id} ${on?"einschalten":"ausschalten"}?`))return;try{diag(`Switching ${id} -> ${on?"ON":"OFF"}…`);const x=await writeApi(`/api/v1/smarthome/devices/${encodeURIComponent(id)}/switch`,{method:"POST",body:JSON.stringify({on})});diag(x);await refreshPower()}catch(e){diag("SMART PLUG WRITE ERROR\n"+e.message)}}
function candidateCard(row){return `<article class="candidate-card"><div class="candidate-head"><div><span class="provider-tag">${escapeHtml(row.provider)}</span><strong>${escapeHtml(row.name)}</strong><small>${escapeHtml(row.host)}${row.port?":"+row.port:""}</small></div><span class="candidate-source">${escapeHtml(row.metadata?.model||row.source||"")}</span></div><div class="button-row"><button class="secondary" data-probe-provider="${escapeHtml(row.provider)}" data-probe-host="${escapeHtml(row.host)}" data-probe-port="${row.port||""}">VERBINDUNG TESTEN</button><button class="ghost" data-register-provider="${escapeHtml(row.provider)}" data-register-host="${escapeHtml(row.host)}" data-register-name="${escapeHtml(row.name)}">ÜBERNEHMEN</button></div><pre class="probe-result" data-result-host="${escapeHtml(row.host)}">Noch nicht getestet.</pre></article>`}
function bluetoothCard(row){return `<article class="candidate-card"><div class="candidate-head"><div><span class="provider-tag">BLUETOOTH</span><strong>${escapeHtml(row.name||"Unbekanntes BLE-Gerät")}</strong><small>${escapeHtml(row.address)}</small></div><span class="candidate-source">RSSI ${escapeHtml(row.rssi??"?")} dBm</span></div><div class="button-row"><button class="secondary" data-ble-address="${escapeHtml(row.address)}">VERBINDEN & GATT LESEN</button></div><pre class="probe-result" data-ble-result="${escapeHtml(row.address)}">${row.preferred?"Passender DF100M/Mars-Hinweis erkannt.":"Noch nicht getestet."}</pre></article>`}
async function loadProviders(){try{const x=await api("/api/v1/smarthome/onboarding/providers");$("providerGrid").innerHTML=x.providers.map(p=>`<div class="provider-card"><strong>${escapeHtml(p.id).toUpperCase()}</strong><span>${p.control?"Steuerung bereit":escapeHtml(p.note||"Diagnose")}</span></div>`).join("")}catch(e){diag("PROVIDER ERROR\n"+e.message)}}
function bindCandidates(){document.querySelectorAll("[data-probe-provider]").forEach(btn=>btn.addEventListener("click",async()=>{const target=document.querySelector(`[data-result-host="${CSS.escape(btn.dataset.probeHost)}"]`);target.textContent="Teste Verbindung…";try{const x=await writeApi("/api/v1/smarthome/onboarding/probe",{method:"POST",body:JSON.stringify({provider:btn.dataset.probeProvider,host:btn.dataset.probeHost,port:btn.dataset.probePort?Number(btn.dataset.probePort):null})});target.textContent=JSON.stringify(x,null,2);diag(x)}catch(e){target.textContent=e.message}}));document.querySelectorAll("[data-register-provider]").forEach(btn=>btn.addEventListener("click",async()=>{const id=(prompt("Interne Geräte-ID (klein, ohne Leerzeichen)",`${btn.dataset.registerProvider}-${btn.dataset.registerHost.replaceAll(".","-")}`)||"").trim();if(!id)return;try{diag(await writeApi("/api/v1/smarthome/onboarding/register",{method:"POST",body:JSON.stringify({id,name:btn.dataset.registerName,provider:btn.dataset.registerProvider,host:btn.dataset.registerHost})}));await refreshPower()}catch(e){diag("REGISTER ERROR\n"+e.message)}}))}
async function scanSmartHome(){const button=$("smartScanBtn");button.disabled=true;$("scanStatus").textContent="Suche im lokalen Netz…";try{const x=await writeApi("/api/v1/smarthome/onboarding/discover?timeout=5",{method:"POST"});$("scanStatus").textContent=`${x.count} Gerät(e) gefunden.`;$("candidateGrid").innerHTML=x.devices.length?x.devices.map(candidateCard).join(""):'<div class="empty-state">Keine unterstützten Geräte gefunden. Sie müssen eingeschaltet und im selben LAN sein.</div>';bindCandidates();diag(x)}catch(e){$("scanStatus").textContent="Suche fehlgeschlagen: "+e.message;diag("LAN DISCOVERY ERROR\n"+e.message)}finally{button.disabled=false}}
$("smartScanBtn")?.addEventListener("click",scanSmartHome);loadProviders();
async function scanBluetooth(){const button=$("bleScanBtn");button.disabled=true;$("scanStatus").textContent="Bluetooth-Umgebung wird gescannt…";try{const x=await writeApi("/api/df100m/discover?timeout=8");$("scanStatus").textContent=`${x.devices?.length||0} Bluetooth-Gerät(e) gefunden.`;$("candidateGrid").innerHTML=x.devices?.length?x.devices.map(bluetoothCard).join(""):'<div class="empty-state">Keine BLE-Geräte gefunden.</div>';document.querySelectorAll("[data-ble-address]").forEach(btn=>btn.addEventListener("click",async()=>{const target=document.querySelector(`[data-ble-result="${CSS.escape(btn.dataset.bleAddress)}"]`);target.textContent="Verbinde…";try{const connected=await writeApi("/api/df100m/connect?address="+encodeURIComponent(btn.dataset.bleAddress),{method:"POST"});const services=await writeApi("/api/df100m/services");target.textContent=JSON.stringify({connected,services},null,2);diag({connected,services})}catch(e){target.textContent=e.message}}))}catch(e){$("scanStatus").textContent="Bluetooth-Suche fehlgeschlagen: "+e.message}finally{button.disabled=false}}
$("bleScanBtn")?.addEventListener("click",scanBluetooth);
$("tapoAccountForm")?.addEventListener("submit",async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;$("scanStatus").textContent="Tapo-Geräte werden mit den eingegebenen Zugangsdaten gesucht…";try{const x=await writeApi("/api/v1/smarthome/onboarding/discover/account",{method:"POST",body:JSON.stringify({provider:"tapo",username:$("tapoUsername").value,password:$("tapoPassword").value,timeout:6})});$("tapoPassword").value="";$("scanStatus").textContent=`${x.count} Tapo/TP-Link-Gerät(e) gefunden. Zugangsdaten gespeichert: nein.`;$("candidateGrid").innerHTML=x.devices.length?x.devices.map(candidateCard).join(""):'<div class="empty-state">Keine Tapo/TP-Link-Geräte gefunden. Konto, WLAN und Gerätefreigabe prüfen.</div>';bindCandidates();diag({count:x.count,credentials_stored:x.credentials_stored,devices:x.devices})}catch(e){$("tapoPassword").value="";$("scanStatus").textContent="Tapo-Suche fehlgeschlagen: "+e.message}finally{button.disabled=false}});
async function loadSystemDiagnostics(){const button=$("loadDiagnosticsBtn");button.disabled=true;$("systemDiagnostics").textContent="Lade Dienststatus und Journal…";try{$("systemDiagnostics").textContent=JSON.stringify(await writeApi("/api/v1/diagnostics/snapshot?lines=80"),null,2)}catch(e){$("systemDiagnostics").textContent="DIAGNOSEFEHLER\n"+e.message}finally{button.disabled=false}}
$("loadDiagnosticsBtn")?.addEventListener("click",loadSystemDiagnostics);
$("discoverBtn").addEventListener("click",async()=>{diag("Scanning BLE…");try{const x=await writeApi("/api/df100m/discover");diag(x);if(x.devices?.length){const d=x.devices[0];diag(await writeApi("/api/df100m/connect?address="+encodeURIComponent(d.address),{method:"POST"}));refreshStatus()}}catch(e){diag("DISCOVERY ERROR\n"+e.message)}});
$("servicesBtn").addEventListener("click",async()=>{diag("Reading GATT services…");try{diag(await writeApi("/api/df100m/services"))}catch(e){diag("GATT ERROR\n"+e.message)}});
$("sendSpeedBtn").addEventListener("click",async()=>{const v=Number(slider.value);if(!confirm(`Experimentellen DF100M-Testbefehl mit ${v}% senden?`))return;try{diag(await writeApi(`/api/df100m/speed?percent=${v}`,{method:"POST"}))}catch(e){diag("WRITE ERROR\n"+e.message)}});
async function refreshAll(){await Promise.allSettled([refreshStatus(),refreshPower()])}
$("refreshBtn").addEventListener("click",refreshAll);setInterval(refreshAll,5000);updateProjection();refreshAll();
