const $=id=>document.getElementById(id);
const esc=v=>String(v??'--').replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[c]));
const labels={dashboard:'Dashboard',power:'Energie & Steckdosen',history:'Historie & Kosten',devices:'Geräte',camera:'Kamera',automation:'Automation',system:'System'};
function tick(){$('clock').textContent=new Date().toLocaleTimeString('de-DE')}setInterval(tick,1000);tick();
function show(panel){$('legacyPanel').classList.toggle('active',panel==='legacy');$('systemPanel').classList.toggle('active',panel==='system')}
function selectNav(button){document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x===button))}
function openLegacy(view){show('legacy');$('pageTitle').textContent=labels[view]||'Grow Central';const frame=$('legacyFrame');const activate=()=>{try{const d=frame.contentDocument;if(!d)return;const btn=d.querySelector(`[data-view="${view}"]`);if(btn)btn.click();const style=d.createElement('style');style.textContent='.sidebar,.topbar{display:none!important}.app-shell{display:block!important}.main{margin:0!important;width:100%!important}.view{padding-top:18px!important}';d.head.appendChild(style)}catch{}};if(frame.contentDocument?.readyState==='complete')activate();else frame.addEventListener('load',activate,{once:true})}
function focusSystem(tab){show('system');$('pageTitle').textContent=tab==='network'?'System · Netzwerk':tab==='build'?'System · Build & Version':'System · Hostsystem';document.querySelectorAll('[data-system-tab]').forEach(card=>card.classList.toggle('focus',card.dataset.systemTab===tab));const card=document.querySelector(`[data-system-tab="${tab}"]`);if(card)card.scrollIntoView({behavior:'smooth',block:'center'});refreshSystem()}
document.querySelectorAll('.nav-link').forEach(btn=>btn.addEventListener('click',()=>{selectNav(btn);const [kind,target]=btn.dataset.target.split(':');kind==='legacy'?openLegacy(target):focusSystem(target)}));
function dl(rows){return rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}
function bytes(v){const n=Number(v);if(!Number.isFinite(n))return '--';const units=['B','KB','MB','GB','TB'];let x=n,i=0;while(x>=1024&&i<units.length-1){x/=1024;i++}return `${x.toFixed(i>1?1:0)} ${units[i]}`}
async function api(url,options={}){const r=await fetch(url,{cache:'no-store',...options});if(r.status===401){location.href='/login';throw new Error('Login erforderlich')}if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
async function refreshSystem(){try{const x=await api('/api/v1/system/info');$('hostState').textContent='ONLINE';$('hostTitle').textContent=x.hostname||'Raspberry Pi';$('topBuild').textContent=`BUILD ${x.build||'--'}`;$('cpuLoad').textContent=x.resources?.cpu_percent!=null?`${Number(x.resources.cpu_percent).toFixed(0)} %`:'--';$('cpuTemp').textContent=x.resources?.cpu_temperature_c!=null?`${Number(x.resources.cpu_temperature_c).toFixed(1)} °C`:'-- °C';$('memoryUsage').textContent=x.resources?.memory_percent!=null?`${Number(x.resources.memory_percent).toFixed(0)} %`:'--';$('memoryDetail').textContent=x.resources?`${bytes(x.resources.memory_used_bytes)} / ${bytes(x.resources.memory_total_bytes)}`:'--';$('diskUsage').textContent=x.resources?.disk_percent!=null?`${Number(x.resources.disk_percent).toFixed(0)} %`:'--';$('diskDetail').textContent=x.resources?`${bytes(x.resources.disk_used_bytes)} / ${bytes(x.resources.disk_total_bytes)}`:'--';$('uptime').textContent=x.uptime?.display||'--';$('loadAverage').textContent=x.resources?.load_average?`Load ${x.resources.load_average.map(v=>Number(v).toFixed(2)).join(' / ')}`:'Load --';$('hostData').innerHTML=dl([['Hostname',x.hostname],['Modell',x.model],['Betriebssystem',x.operating_system],['Kernel',x.kernel],['Architektur',x.architecture],['Primäre IPv4',x.primary_ipv4||'--']]);$('buildData').innerHTML=dl([['Version',x.version],['Build',x.build],['Release-Kanal',x.release_channel||'local'],['API',x.api_version||x.version],['Boot-Profil',x.hardware?.profile||x.hardware?.family||'--']]);$('buildStatus').textContent=x.build_status||`Installierter Stand: ${x.version||'--'} · Build ${x.build||'--'}`;$('hardwareData').innerHTML=dl([['Board',x.hardware?.model||x.model],['Serienklasse',x.hardware?.family||'Raspberry Pi'],['CPU-Kerne',x.resources?.cpu_count||'--'],['Plattform',x.hardware?.profile||'--'],['WLAN',x.hardware?.wifi_interface||'--']]);$('networkData').innerHTML=(x.interfaces||[]).filter(i=>i.name!=='lo').map(i=>`<div class="iface"><strong><span>${esc(i.name)}</span><span>${esc(i.state)}</span></strong><small>${(i.addresses||[]).map(a=>`${esc(a.family)} ${esc(a.address)}/${esc(a.prefix)}`).join(' · ')||'Keine Adresse'}</small></div>`).join('')||'<div class="iface">Keine Netzwerkschnittstelle erkannt.</div>'}catch(e){$('hostState').textContent='OFFLINE';$('buildStatus').textContent=`Systemdaten nicht verfügbar: ${e.message}`}}
$('syncBtn').addEventListener('click',()=>{const system=$('systemPanel').classList.contains('active');system?refreshSystem():$('legacyFrame').contentWindow?.location.reload()});$('logoutBtn').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}location.href='/login'});
openLegacy('dashboard');refreshSystem();
