const $=id=>document.getElementById(id);
const esc=v=>String(v??'--').replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[c]));
const labels={dashboard:'Dashboard',power:'Energie & Steckdosen',history:'Historie & Kosten',devices:'Geräte',camera:'Kamera',automation:'Automation',system:'System'};
let rooms=[],activeRoom=null,roomTab='overview';
function tick(){$('clock').textContent=new Date().toLocaleTimeString('de-DE')}setInterval(tick,1000);tick();
function show(panel){['legacy','system','rooms'].forEach(x=>$(x+'Panel').classList.toggle('active',panel===x))}
function selectNav(button){document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x===button))}
function openLegacy(view){show('legacy');$('pageTitle').textContent=labels[view]||'Grow Central';const frame=$('legacyFrame');const activate=()=>{try{const d=frame.contentDocument;if(!d)return;const btn=d.querySelector(`[data-view="${view}"]`);if(btn)btn.click();const style=d.createElement('style');style.textContent='.sidebar,.topbar{display:none!important}.app-shell{display:block!important}.main{margin:0!important;width:100%!important}.view{padding-top:18px!important}';d.head.appendChild(style)}catch{}};if(frame.contentDocument?.readyState==='complete')activate();else frame.addEventListener('load',activate,{once:true})}
function focusSystem(tab){show('system');$('pageTitle').textContent=tab==='network'?'System · Netzwerk':tab==='build'?'System · Build & Version':'System · Hostsystem';document.querySelectorAll('[data-system-tab]').forEach(card=>card.classList.toggle('focus',card.dataset.systemTab===tab));document.querySelector(`[data-system-tab="${tab}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});refreshSystem()}
function openRooms(tab='overview'){show('rooms');$('pageTitle').textContent='Räume & Growtagebuch';roomTab=tab==='manage'?'overview':tab;refreshRooms().then(()=>{if(activeRoom)selectRoom(activeRoom.id,roomTab)})}
document.querySelectorAll('.nav-link').forEach(btn=>btn.addEventListener('click',()=>{selectNav(btn);const [kind,target]=btn.dataset.target.split(':');kind==='legacy'?openLegacy(target):kind==='system'?focusSystem(target):openRooms(target)}));
function dl(rows){return rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}
function bytes(v){const n=Number(v);if(!Number.isFinite(n))return '--';const units=['B','KB','MB','GB','TB'];let x=n,i=0;while(x>=1024&&i<units.length-1){x/=1024;i++}return `${x.toFixed(i>1?1:0)} ${units[i]}`}
async function api(url,options={}){const r=await fetch(url,{cache:'no-store',...options});if(r.status===401){location.href='/login';throw new Error('Login erforderlich')}let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||`${r.status} ${r.statusText}`);return data}
function writeToken(){let token=sessionStorage.getItem('gcLocalWriteToken')||'';if(!token){token=prompt('Lokales Grow Central Write-Token eingeben. Es wird nur für diese Browser-Sitzung gespeichert.')||'';if(token)sessionStorage.setItem('gcLocalWriteToken',token)}return token}
async function writeApi(url,options={}){const token=writeToken();if(!token)throw new Error('Kein Write-Token angegeben');const headers=new Headers(options.headers||{});headers.set('X-API-Token',token);headers.set('Content-Type','application/json');try{return await api(url,{...options,headers})}catch(e){if(/token|auth|403/i.test(e.message))sessionStorage.removeItem('gcLocalWriteToken');throw e}}
async function refreshSystem(){try{const x=await api('/api/v1/system/info');$('hostState').textContent='ONLINE';$('hostTitle').textContent=x.hostname||'Raspberry Pi';$('topBuild').textContent=`BUILD ${x.build||'--'}`;$('cpuLoad').textContent=x.resources?.cpu_percent!=null?`${Number(x.resources.cpu_percent).toFixed(0)} %`:'--';$('cpuTemp').textContent=x.resources?.cpu_temperature_c!=null?`${Number(x.resources.cpu_temperature_c).toFixed(1)} °C`:'-- °C';$('memoryUsage').textContent=x.resources?.memory_percent!=null?`${Number(x.resources.memory_percent).toFixed(0)} %`:'--';$('memoryDetail').textContent=x.resources?`${bytes(x.resources.memory_used_bytes)} / ${bytes(x.resources.memory_total_bytes)}`:'--';$('diskUsage').textContent=x.resources?.disk_percent!=null?`${Number(x.resources.disk_percent).toFixed(0)} %`:'--';$('diskDetail').textContent=x.resources?`${bytes(x.resources.disk_used_bytes)} / ${bytes(x.resources.disk_total_bytes)}`:'--';$('uptime').textContent=x.uptime?.display||'--';$('loadAverage').textContent=x.resources?.load_average?`Load ${x.resources.load_average.map(v=>Number(v).toFixed(2)).join(' / ')}`:'Load --';$('hostData').innerHTML=dl([['Hostname',x.hostname],['Modell',x.model],['Betriebssystem',x.operating_system],['Kernel',x.kernel],['Architektur',x.architecture],['Primäre IPv4',x.primary_ipv4||'--']]);$('buildData').innerHTML=dl([['Version',x.version],['Build',x.build],['Release-Kanal',x.release_channel||'local'],['API',x.api_version||x.version],['Boot-Profil',x.hardware?.profile||x.hardware?.family||'--']]);$('buildStatus').textContent=x.build_status||`Installierter Stand: ${x.version||'--'} · Build ${x.build||'--'}`;$('hardwareData').innerHTML=dl([['Board',x.hardware?.model||x.model],['Serienklasse',x.hardware?.family||'Raspberry Pi'],['CPU-Kerne',x.resources?.cpu_count||'--'],['Plattform',x.hardware?.profile||'--'],['WLAN',x.hardware?.wifi_interface||'--']]);$('networkData').innerHTML=(x.interfaces||[]).filter(i=>i.name!=='lo').map(i=>`<div class="iface"><strong><span>${esc(i.name)}</span><span>${esc(i.state)}</span></strong><small>${(i.addresses||[]).map(a=>`${esc(a.family)} ${esc(a.address)}/${esc(a.prefix)}`).join(' · ')||'Keine Adresse'}</small></div>`).join('')||'<div class="iface">Keine Netzwerkschnittstelle erkannt.</div>'}catch(e){$('hostState').textContent='OFFLINE';$('buildStatus').textContent=`Systemdaten nicht verfügbar: ${e.message}`}}
const kindLabel={grow_tent:'Growzelt',grow_room:'Growraum',drying:'Trocknung',storage:'Lager',other:'Sonstiges'};
function roomCard(r){const s=r.latest_sensor||{};return `<button class="room-card ${activeRoom?.id===r.id?'active':''}" data-room-id="${esc(r.id)}"><span>${esc(kindLabel[r.kind]||r.kind)}</span><strong>${esc(r.name)}</strong><div><b>${s.temperature_c!=null?Number(s.temperature_c).toFixed(1)+' °C':'-- °C'}</b><b>${s.humidity_percent!=null?Number(s.humidity_percent).toFixed(0)+' %':'-- %'}</b></div><small>${r.device_count||0} Geräte · ${r.plant_count||0} Pflanzen</small></button>`}
async function refreshRooms(){const x=await api('/api/v1/rooms');rooms=x.rooms||[];if(activeRoom)activeRoom=rooms.find(r=>r.id===activeRoom.id)||null;$('roomCards').innerHTML=rooms.length?rooms.map(roomCard).join(''):'<div class="empty-room">Noch keine Räume angelegt.</div>';$('roomList').innerHTML=rooms.length?rooms.map(r=>`<button class="room-list-item ${activeRoom?.id===r.id?'active':''}" data-room-id="${esc(r.id)}"><strong>${esc(r.name)}</strong><small>${esc(kindLabel[r.kind]||r.kind)}</small></button>`).join(''):'<div class="empty-room">Keine Räume</div>';document.querySelectorAll('[data-room-id]').forEach(b=>b.addEventListener('click',()=>selectRoom(b.dataset.roomId,roomTab)));if(!activeRoom&&rooms.length)await selectRoom(rooms[0].id,roomTab);else renderRoomHeader()}
function setRoomTab(tab){roomTab=tab;document.querySelectorAll('.room-tab').forEach(b=>b.classList.toggle('active',b.dataset.roomTab===tab));document.querySelectorAll('.room-tabpage').forEach(p=>p.classList.toggle('active',p.dataset.roomPage===tab));if(activeRoom){if(tab==='devices')loadRoomDevices();if(tab==='sensors')loadSensors();if(tab==='journal')loadRoomJournal();if(tab==='plants')loadPlants()}}
async function selectRoom(id,tab='overview'){activeRoom=rooms.find(r=>r.id===id)||null;renderRoomHeader();document.querySelectorAll('[data-room-id]').forEach(b=>b.classList.toggle('active',b.dataset.roomId===id));setRoomTab(['overview','devices','sensors','journal','plants'].includes(tab)?tab:'overview');if(activeRoom)await loadRoomJournal(true)}
function renderRoomHeader(){const on=!!activeRoom;$('roomEmpty').hidden=on;$('roomContent').hidden=!on;if(!on)return;const r=activeRoom,s=r.latest_sensor||{};$('roomKind').textContent=(kindLabel[r.kind]||r.kind).toUpperCase();$('roomName').textContent=r.name;$('roomDescription').textContent=r.description||'Keine Beschreibung';$('roomTemp').textContent=s.temperature_c!=null?`${Number(s.temperature_c).toFixed(1)} °C`:'--';$('roomHumidity').textContent=s.humidity_percent!=null?`${Number(s.humidity_percent).toFixed(0)} %`:'--';$('roomVpd').textContent=s.vpd_kpa!=null?Number(s.vpd_kpa).toFixed(2):'--';$('roomCounts').textContent=`${r.device_count||0} / ${r.plant_count||0}`;$('roomTargets').innerHTML=dl([['Temperatur',r.target_temperature_c!=null?`${r.target_temperature_c} °C`:'nicht gesetzt'],['Luftfeuchte',r.target_humidity_percent!=null?`${r.target_humidity_percent} %`:'nicht gesetzt'],['Lichtzyklus',r.light_cycle||'nicht gesetzt']])}
async function createOrEditRoom(edit=false){const r=edit?activeRoom:null;if(edit&&!r)return;const name=prompt('Raumname',r?.name||'')?.trim();if(!name)return;const kind=prompt('Raumtyp: grow_tent, grow_room, drying, storage, other',r?.kind||'grow_tent')||'grow_tent';const description=prompt('Beschreibung',r?.description||'')||'';const temp=prompt('Solltemperatur °C (leer = keine)',r?.target_temperature_c??'');const rh=prompt('Soll-Luftfeuchte % (leer = keine)',r?.target_humidity_percent??'');const light=prompt('Lichtzyklus, z.B. 18/6',r?.light_cycle||'')||'';const body={name,kind,description,target_temperature_c:temp===''?null:Number(temp),target_humidity_percent:rh===''?null:Number(rh),light_cycle:light};const saved=await writeApi(edit?`/api/v1/rooms/${r.id}`:'/api/v1/rooms',{method:edit?'PUT':'POST',body:JSON.stringify(body)});activeRoom=saved;await refreshRooms()}
async function loadRoomDevices(){if(!activeRoom)return;const x=await api(`/api/v1/rooms/${activeRoom.id}/devices`);$('roomDevices').innerHTML=x.devices.length?x.devices.map(d=>`<article class="assignment-card"><div><span>${esc(d.adapter)}</span><strong>${esc(d.name)}</strong><small>${d.room_id&&d.room_id!==activeRoom.id?'Bereits anderem Raum zugeordnet':'Geräte-ID: '+esc(d.id)}</small></div><button class="${d.assigned?'assigned':''}" data-assign-device="${esc(d.id)}" data-assigned="${d.assigned}">${d.assigned?'ZUGEORDNET':'ZUORDNEN'}</button></article>`).join(''):'<div class="empty-room">Noch keine registrierten Smart-Home-Geräte.</div>';document.querySelectorAll('[data-assign-device]').forEach(b=>b.addEventListener('click',async()=>{try{if(b.dataset.assigned==='true')await writeApi(`/api/v1/rooms/${activeRoom.id}/devices/${encodeURIComponent(b.dataset.assignDevice)}`,{method:'DELETE'});else await writeApi(`/api/v1/rooms/${activeRoom.id}/devices`,{method:'POST',body:JSON.stringify({device_id:b.dataset.assignDevice})});await refreshRooms();await loadRoomDevices()}catch(e){alert(e.message)}}))}
async function loadSensors(){if(!activeRoom)return;const x=await api(`/api/v1/rooms/${activeRoom.id}/sensors?limit=250`),rows=x.samples||[],last=rows.at(-1)||{};$('sensorSummary').innerHTML=`<article><span>MESSPUNKTE</span><strong>${rows.length}</strong><small>letzte 250</small></article><article><span>LETZTE TEMP.</span><strong>${last.temperature_c!=null?Number(last.temperature_c).toFixed(1)+' °C':'--'}</strong><small>${last.timestamp?new Date(last.timestamp).toLocaleString('de-DE'):'--'}</small></article><article><span>LETZTE FEUCHTE</span><strong>${last.humidity_percent!=null?Number(last.humidity_percent).toFixed(0)+' %':'--'}</strong><small>VPD ${last.vpd_kpa??'--'}</small></article><article><span>LEISTUNG</span><strong>${last.power_w!=null?Number(last.power_w).toFixed(1)+' W':'--'}</strong><small>Raumsumme</small></article>`;$('sensorRows').innerHTML=rows.length?[...rows].reverse().map(s=>`<tr><td>${new Date(s.timestamp).toLocaleString('de-DE')}</td><td>${s.temperature_c??'--'} °C</td><td>${s.humidity_percent??'--'} %</td><td>${s.vpd_kpa??'--'}</td><td>${s.power_w??'--'} W</td><td>${s.energy_wh??'--'} Wh</td><td>${esc(s.source)}</td></tr>`).join(''):'<tr><td colspan="7">Noch keine Messwerte gespeichert.</td></tr>'}
function journalHtml(entries){return entries?.length?entries.map(e=>`<article class="journal-entry"><div><span>${esc(e.category)}</span><time>${new Date(e.created_at).toLocaleString('de-DE')}</time></div><strong>${esc(e.title)}</strong><p>${esc(e.text||'')}</p></article>`).join(''):'<div class="empty-room">Noch keine Tagebucheinträge.</div>'}
async function loadRoomJournal(silent=false){if(!activeRoom)return;const x=await api(`/api/v1/rooms/${activeRoom.id}/journal`);$('roomJournal').innerHTML=journalHtml(x.entries);$('roomLastJournal').innerHTML=journalHtml((x.entries||[]).slice(0,1));if(!silent&&roomTab==='journal')$('roomJournal').scrollTop=0}
async function addRoomJournal(){if(!activeRoom)return;const title=prompt('Titel des Tagebucheintrags')?.trim();if(!title)return;const category=prompt('Kategorie: note, watering, feeding, training, defoliation, pest, flowering, harvest, other','note')||'note';const text=prompt('Notiz / Beobachtung','')||'';await writeApi(`/api/v1/rooms/${activeRoom.id}/journal`,{method:'POST',body:JSON.stringify({title,category,text})});await loadRoomJournal();await refreshRooms()}
async function loadPlants(){if(!activeRoom)return;const x=await api(`/api/v1/rooms/${activeRoom.id}/plants`);$('plantGrid').innerHTML=x.plants.length?x.plants.map(p=>`<article class="plant-card"><span>${esc(p.phase)}</span><strong>${esc(p.name)}</strong><small>${esc(p.strain||'Sorte nicht angegeben')} · ${esc(p.plant_type)}</small><p>${esc(p.notes||'')}</p><div><button data-plant-journal="${esc(p.id)}">TAGEBUCH</button><button data-edit-plant="${esc(p.id)}">BEARBEITEN</button></div></article>`).join(''):'<div class="empty-room">Noch keine Pflanzen angelegt.</div>';document.querySelectorAll('[data-plant-journal]').forEach(b=>b.addEventListener('click',()=>plantJournal(b.dataset.plantJournal)));document.querySelectorAll('[data-edit-plant]').forEach(b=>b.addEventListener('click',()=>editPlant(b.dataset.editPlant,x.plants)))}
async function addPlant(existing=null){if(!activeRoom)return;const name=prompt('Pflanzenname',existing?.name||'')?.trim();if(!name)return;const strain=prompt('Sorte / Strain',existing?.strain||'')||'';const plant_type=prompt('Typ: automatic, feminized, mother, clone, other',existing?.plant_type||'automatic')||'other';const start_date=prompt('Startdatum (YYYY-MM-DD)',existing?.start_date||new Date().toISOString().slice(0,10))||'';const phase=prompt('Phase: germination, vegetative, flowering, flush, harvest, other',existing?.phase||'vegetative')||'vegetative';const notes=prompt('Notizen',existing?.notes||'')||'';const url=existing?`/api/v1/rooms/${activeRoom.id}/plants/${existing.id}`:`/api/v1/rooms/${activeRoom.id}/plants`;await writeApi(url,{method:existing?'PUT':'POST',body:JSON.stringify({name,strain,plant_type,start_date,phase,notes})});await loadPlants();await refreshRooms()}
function editPlant(id,list){addPlant(list.find(p=>p.id===id))}
async function plantJournal(id){const x=await api(`/api/v1/rooms/${activeRoom.id}/plants/${id}/journal`);const history=(x.entries||[]).slice(0,5).map(e=>`${new Date(e.created_at).toLocaleDateString('de-DE')} · ${e.title}: ${e.text}`).join('\n\n')||'Noch keine Einträge.';if(!confirm(`Letzte Pflanzeneinträge:\n\n${history}\n\nNeuen Eintrag hinzufügen?`))return;const title=prompt('Titel')?.trim();if(!title)return;const category=prompt('Kategorie','note')||'note';const text=prompt('Notiz','')||'';await writeApi(`/api/v1/rooms/${activeRoom.id}/plants/${id}/journal`,{method:'POST',body:JSON.stringify({title,category,text})});alert('Pflanzentagebuch gespeichert.')}
document.querySelectorAll('.room-tab').forEach(b=>b.addEventListener('click',()=>setRoomTab(b.dataset.roomTab)));
$('newRoomBtn').addEventListener('click',()=>createOrEditRoom(false).catch(e=>alert(e.message)));$('editRoomBtn').addEventListener('click',()=>createOrEditRoom(true).catch(e=>alert(e.message)));$('addRoomJournalBtn').addEventListener('click',()=>addRoomJournal().catch(e=>alert(e.message)));$('addPlantBtn').addEventListener('click',()=>addPlant().catch(e=>alert(e.message)));$('captureRoomBtn').addEventListener('click',async()=>{try{await writeApi('/api/v1/rooms/capture',{method:'POST'});await refreshRooms();await loadSensors()}catch(e){alert(e.message)}});
$('syncBtn').addEventListener('click',()=>{if($('systemPanel').classList.contains('active'))refreshSystem();else if($('roomsPanel').classList.contains('active'))refreshRooms();else $('legacyFrame').contentWindow?.location.reload()});$('logoutBtn').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}location.href='/login'});
openLegacy('dashboard');refreshSystem();
