(() => {
  const $=(id)=>document.getElementById(id); const esc=(v)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const app={mode:localStorage.getItem('gc.mode')==='advanced'?'advanced':'simple',smart:null,discovered:[],filter:'all'};
  async function api(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
  const fmt=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
  function toast(msg,type=''){const n=$('mToast');n.textContent=msg;n.className=`mtoast show ${type}`.trim();clearTimeout(toast.t);toast.t=setTimeout(()=>n.className='mtoast',3000)}
  function mode(value){app.mode=value==='advanced'?'advanced':'simple';localStorage.setItem('gc.mode',app.mode);document.documentElement.dataset.mode=app.mode;$('mSimple').classList.toggle('active',app.mode==='simple');$('mAdvanced').classList.toggle('active',app.mode==='advanced')}
  function tab(name){const map={overview:'mOverview',grow:'mGrow',devices:'mDevices',automation:'mAutomation',camera:'mCamera',more:'mMore'};document.querySelectorAll('.mview').forEach(n=>n.classList.toggle('active',n.id===map[name]));document.querySelectorAll('.bottom-nav [data-tab]').forEach(n=>n.classList.toggle('active',n.dataset.tab===name));if(name==='automation')loadAutomations();if(name==='camera')loadCamera();if(name==='more')loadMore();if(name==='devices')renderDevices()}
  function row(r){const s=r.state||{};const values=[];if(s.power_w!=null)values.push(`${fmt(s.power_w)} W`);if(s.temperature!=null)values.push(`${fmt(s.temperature)} °C`);if(s.humidity!=null)values.push(`${fmt(s.humidity,0)} %`);return `<div class="mrow"><div><strong>${esc(r.name||r.id||r.native_id)}</strong><small>${esc([r.adapter||r.provider_id,...values].filter(Boolean).join(' · ')||r.device_class||'Gerät')}</small></div><span class="mbadge ${r.online===false?'offline':''}">${r.online===false?'OFFLINE':'ONLINE'}</span></div>`}
  function discoveredCard(r){return `<div class="mrow" data-kind="${esc(r.device_class||'')}"><div><strong>${esc(r.name||r.native_id)}</strong><small>${esc(`${r.provider_id} · ${(r.capabilities||[]).slice(0,3).join(', ')}`)}</small></div><span class="mbadge">ERKANNT</span></div>`}
  function renderDevices(){let legacy=app.smart?.devices||[];let discoveredRows=app.discovered||[];if(app.filter==='online')legacy=legacy.filter(x=>x.online!==false);else if(app.filter!=='all'){legacy=legacy.filter(x=>(x.type||'switch')===app.filter);discoveredRows=discoveredRows.filter(x=>x.device_class===app.filter)}$('mDeviceList').innerHTML=[...legacy.map(row),...discoveredRows.map(discoveredCard)].join('')||'<div class="mempty">Keine Geräte für diesen Filter.</div>'}
  async function loadBase(refresh=false){
    const results=await Promise.allSettled([api('/api/health'),api('/api/devices/runtime'),api(`/api/v1/smarthome/overview${refresh?'?refresh=true':''}`),api('/api/status')]);
    const health=results[0].status==='fulfilled'&&results[0].value?.ok; const runtime=results[1].status==='fulfilled'?results[1].value:null; const smart=results[2].status==='fulfilled'?results[2].value:null; const status=results[3].status==='fulfilled'?results[3].value:null; app.smart=smart;
    $('connectionLabel').textContent=health?'LOCAL ONLINE':'CORE OFFLINE'; const errors=(runtime?.providers||[]).filter(x=>x.error).length; const statusBox=$('mStatus');statusBox.classList.remove('warning','error');
    if(!health){statusBox.classList.add('error');$('mHeadline').textContent='Core nicht erreichbar';$('mHeadlineSub').textContent='Raspberry Pi oder Dienst prüfen.'}else if(errors){statusBox.classList.add('warning');$('mHeadline').textContent='Grow Central läuft mit Hinweisen';$('mHeadlineSub').textContent=`${errors} Provider melden Verbindungsprobleme.`}else{$('mHeadline').textContent='Alles läuft normal';$('mHeadlineSub').textContent='Lokaler Core und Plattform sind bereit.'}
    let temp=null,rh=null,vpd=null;for(const n of (status?.notifications||[]).slice().reverse()){if(temp==null&&Number.isFinite(Number(n.temperature)))temp=Number(n.temperature);if(rh==null&&Number.isFinite(Number(n.humidity)))rh=Number(n.humidity);if(vpd==null&&Number.isFinite(Number(n.vpd)))vpd=Number(n.vpd)}if(vpd==null&&temp!=null&&rh!=null){const es=.6108*Math.exp(17.27*temp/(temp+237.3));vpd=es*(1-rh/100)}$('mTemp').textContent=temp==null?'—':fmt(temp);$('mRh').textContent=rh==null?'—':fmt(rh,0);$('mVpd').textContent=vpd==null?'—':fmt(vpd,2);
    const summary=smart?.summary||{};$('mPower').textContent=Number.isFinite(Number(summary.power_w))?fmt(summary.power_w):'—';$('mDeviceCount').textContent=`${summary.online||0} / ${summary.configured||(smart?.devices||[]).length||0}`;$('mDevicePreview').innerHTML=(smart?.devices||[]).length?(smart.devices||[]).slice(0,5).map(row).join(''):'<div class="mempty">Noch keine Geräte registriert.</div>';
    const providers=runtime?.providers||[];$('mRuntimeCount').textContent=`${providers.filter(x=>!x.error).length}/${providers.length}`;$('mRuntimePreview').innerHTML=providers.slice(0,6).map(x=>`<div class="mrow"><div><strong>${esc(x.name)}</strong><small>${x.error?esc(x.error):`${x.device_count} Gerät(e)`}</small></div><span class="mbadge ${x.error?'warning':''}">${x.error?'CHECK':'READY'}</span></div>`).join('')||'<div class="mempty">Keine Runtime-Daten.</div>';renderDevices();
  }
  async function discoverAll(){const b=$('mDiscover');b.disabled=true;b.textContent='Suche…';try{const d=await api('/api/devices/discover?timeout=5');app.discovered=d.devices||[];renderDevices();toast(`${app.discovered.length} Gerät(e) erkannt${(d.errors||[]).length?` · ${(d.errors||[]).length} Hinweise`:''}`,'success')}catch(e){toast(`Discovery: ${e.message}`,'error')}finally{b.disabled=false;b.textContent='Suchen'}}
  async function loadAutomations(){try{const d=await api('/api/v1/automations');const rows=d.automations||[];$('mAutomationList').innerHTML=rows.length?rows.map(r=>`<div class="mrow"><div><strong>${esc(r.name||'Automation')}</strong><small>${esc([r.trigger,r.device_id].filter(Boolean).join(' · '))}</small></div><span class="mbadge ${r.enabled===false?'offline':''}">${r.enabled===false?'PAUSE':'AKTIV'}</span></div>`).join(''):'<div class="mempty">Noch keine Automationen.</div>'}catch(e){$('mAutomationList').innerHTML=`<div class="mempty">${esc(e.message)}</div>`}}
  async function loadCamera(){try{const d=await api('/api/v1/camera/status?refresh=true');const rows=d.devices||[];$('mCameraList').innerHTML=rows.length?rows.map(r=>`<article class="mcam"><div class="preview">◉</div><footer><strong>${esc(r.c920_match?'Logitech C920':r.name||r.device||'Kamera')}</strong><small>${r.capture_capable?'Capture bereit':'Gerät erkannt · prüfen'}</small></footer></article>`).join(''):'<div class="mempty">Keine Kamera erkannt.</div>'}catch(e){$('mCameraList').innerHTML=`<div class="mempty">${esc(e.message)}</div>`}}
  async function loadMore(){if(app.mode!=='advanced')return;try{const [sys,smart]=await Promise.all([api('/api/v1/system/info'),api('/api/v1/smarthome/overview')]);const pairs=[['Hostname',sys.hostname],['IP',sys.primary_ipv4],['Version',sys.version],['Build',sys.build],['Uptime',sys.uptime?.display]];$('mSystem').innerHTML=pairs.map(([a,b])=>`<span>${esc(a)}</span><b>${esc(b||'—')}</b>`).join('');$('mEnergy').textContent=Number.isFinite(Number(smart.summary?.energy_wh))?fmt(Number(smart.summary.energy_wh)/1000,3):'—'}catch(e){toast(`System: ${e.message}`,'error')}}
  document.querySelectorAll('[data-tab]').forEach(n=>n.addEventListener('click',()=>tab(n.dataset.tab)));document.querySelectorAll('[data-mfilter]').forEach(n=>n.addEventListener('click',()=>{document.querySelectorAll('[data-mfilter]').forEach(x=>x.classList.remove('active'));n.classList.add('active');app.filter=n.dataset.mfilter;renderDevices()}));$('mSimple').onclick=()=>mode('simple');$('mAdvanced').onclick=()=>{mode('advanced');loadMore()};$('mRefresh').onclick=()=>loadBase(true).then(()=>toast('Daten aktualisiert','success')).catch(e=>toast(e.message,'error'));$('mDiscover').onclick=discoverAll;$('desktopMode').onclick=()=>{localStorage.setItem('gc.desktop','1');location.assign('/')};mode(app.mode);loadBase(false);setInterval(()=>loadBase(false),60000);
})();