(() => {
  const $ = (id) => document.getElementById(id);
  const esc = (v) => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const titles = {dashboard:"Grow Environment",grow:"Grow Workspace",devices:"Geräte & Provider",automation:"Automation",energy:"Energie",camera:"Kamera",system:"System"};
  async function api(path){const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
  function view(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('pageTitle').textContent=titles[id]||'Grow Central';if(id==='devices')loadDevices();if(id==='automation')loadAutomations();if(id==='energy')loadEnergy();if(id==='camera')loadCamera();if(id==='system')loadSystem()}
  document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.open)));
  function supportLabel(s){return ({detected:'DETECTED',experimental:'EXPERIMENTAL',compatible:'COMPATIBLE',validated:'VALIDATED',certified:'CERTIFIED'})[s]||s.toUpperCase()}
  function providerCard(p){return `<article class="provider-card"><header><h4>${esc(p.name)}</h4><span class="support ${esc(p.support)}">${supportLabel(p.support)}</span></header><p>${esc(p.notes||'Universal Device Provider')}</p><div class="tags">${(p.transports||[]).map(x=>`<span>${esc(x)}</span>`).join('')}${p.local_first?'<span>LOCAL-FIRST</span>':''}</div></article>`}
  async function loadPlatform(){try{const d=await api('/api/devices/platform');$('providerCount').textContent=d.providers.length;$('platformApi').textContent=d.api.toUpperCase();$('providerStrip').innerHTML=d.providers.map(p=>`<span class="provider-chip ${esc(p.support)}">${esc(p.name)} · ${supportLabel(p.support)}</span>`).join('');$('providerGrid').innerHTML=d.providers.map(providerCard).join('');$('coreState').textContent='Universal Device API bereit';$('healthGrid').innerHTML='<div><span>API</span><strong>GC-DEVICE-V1</strong></div><div><span>Local</span><strong>AUTHORITATIVE</strong></div><div><span>Cloud</span><strong>OPTIONAL</strong></div><div><span>Fail-safe</span><strong>ACTIVE</strong></div>'}catch(e){$('coreState').textContent='Device API nicht erreichbar';$('coreState').className='status-bad';$('providerGrid').innerHTML=`<div class="empty">Device API Fehler: ${esc(e.message)}</div>`}}
  function stateRow(r){const s=r.state||{};const details=[r.adapter,s.power_w!=null?`${Number(s.power_w).toFixed(1)} W`:null,s.temperature!=null?`${s.temperature} °C`:null].filter(Boolean).join(' · ');return `<div class="row"><div><strong>${esc(r.name||r.id)}</strong><small>${esc(details||'Gerät')}</small></div><span class="state ${r.online?'':'status-warn'}">${r.online?'ONLINE':'OFFLINE'}</span></div>`}
  async function loadSmartHome(){try{const d=await api('/api/v1/smarthome/overview');$('power').textContent=Number(d.summary?.power_w||0).toFixed(1);$('onlineDevices').textContent=`${d.summary?.online||0} Geräte online`;const rows=d.devices||[];$('devicePreview').innerHTML=rows.length?rows.slice(0,6).map(stateRow).join(''):'<div class="empty">Noch keine Geräte registriert.</div>';return d}catch(e){$('devicePreview').innerHTML=`<div class="empty">Smart-Home-Daten nicht verfügbar: ${esc(e.message)}</div>`;return null}}
  async function loadClimate(){try{const d=await api('/api/status');const n=(d.notifications||[]).slice().reverse();let temp=null,rh=null;for(const x of n){if(x.temperature!=null&&temp==null)temp=x.temperature;if(x.humidity!=null&&rh==null)rh=x.humidity}if(temp!=null)$('temp').textContent=temp;if(rh!=null)$('rh').textContent=rh;if(temp!=null&&rh!=null){const es=.6108*Math.exp(17.27*temp/(temp+237.3));$('vpd').textContent=(es*(1-rh/100)).toFixed(2)}}catch{}}
  async function loadDevices(){try{const d=await api('/api/v1/smarthome/overview');$('deviceList').innerHTML=(d.devices||[]).length?d.devices.map(stateRow).join(''):'<div class="empty">Noch keine Geräte registriert. Provider sind bereit für die schrittweise Modellfreigabe.</div>'}catch(e){$('deviceList').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
  async function loadAutomations(){try{const d=await api('/api/v1/automations');const rows=d.automations||[];$('automationList').innerHTML=rows.length?rows.map(r=>`<div class="row"><div><strong>${esc(r.name)}</strong><small>${esc(r.trigger)} · ${esc(r.device_id)}</small></div><span class="state">${r.enabled===false?'PAUSED':'AKTIV'}</span></div>`).join(''):'<div class="empty">Noch keine lokalen Regeln angelegt.</div>'}catch(e){$('automationList').innerHTML=`<div class="empty">Automationen nicht verfügbar: ${esc(e.message)}</div>`}}
  async function loadEnergy(){try{const d=await api('/api/v1/smarthome/overview?refresh=true');const s=d.summary||{};$('energyPower').textContent=Number(s.power_w||0).toFixed(1);$('energyTotal').textContent=(Number(s.energy_wh||0)/1000).toFixed(3);$('energyOnline').textContent=`${s.online||0} / ${s.configured||0}`;$('energyOn').textContent=s.switched_on||0;$('energyDevices').innerHTML=(d.devices||[]).length?d.devices.map(stateRow).join(''):'<div class="empty">Keine Energiedaten.</div>'}catch(e){$('energyDevices').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
  async function loadCamera(){try{const d=await api('/api/v1/camera/status?refresh=true');const rows=d.devices||[];$('cameraState').innerHTML=rows.length?rows.map(r=>`<div class="row"><div><strong>${esc(r.c920_match?'Logitech C920':r.name||r.id)}</strong><small>${esc(r.device||'UVC Camera')}</small></div><span class="state ${r.capture_capable?'':'status-warn'}">${r.capture_capable?'READY':'CHECK'}</span></div>`).join(''):'Keine Kamera erkannt.'}catch(e){$('cameraState').textContent=`Kamera nicht verfügbar: ${e.message}`}}
  async function loadSystem(){try{const d=await api('/api/v1/system/info');$('systemGrid').innerHTML=[["Hostname",d.hostname],["IP",d.primary_ipv4],["Version",`${d.version||'—'} · Build ${d.build||'—'}`],["Hardware",d.model],["OS",d.operating_system],["Uptime",d.uptime?.display]].map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v||'—')}</b></div>`).join('')}catch(e){$('systemGrid').innerHTML=`<div><span>Fehler</span><b>${esc(e.message)}</b></div>`}}
  async function discover(){const b=$('discoverBtn');b.disabled=true;b.textContent='SUCHE…';try{const d=await api('/api/discover?timeout=5');alert(`${(d.devices||[]).length} Bluetooth-Gerät(e) gefunden. Provider-spezifische Discovery wird schrittweise ergänzt.`)}catch(e){alert(`Discovery: ${e.message}`)}finally{b.disabled=false;b.textContent='GERÄTE SUCHEN'}}
  $('discoverBtn')?.addEventListener('click',discover);$('syncBtn')?.addEventListener('click',async()=>{await Promise.allSettled([loadPlatform(),loadSmartHome(),loadClimate()])});
  setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})},1000);
  Promise.allSettled([api('/api/health'),loadPlatform(),loadSmartHome(),loadClimate()]).then(r=>{const h=r[0];if(h.status==='fulfilled'){$('sideCore').textContent='LOCAL ONLINE'}else{$('sideCore').textContent='CORE OFFLINE';$('sideCore').className='status-bad'}});
})();
