(() => {
  const esc=(v)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const fmt=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
  async function api(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
  function sensor(room){return room?.latest_sensor||{};}
  function status(room){const s=sensor(room);const t=s.temperature_c;const rh=s.humidity_percent;const v=s.vpd_kpa;return [t!=null?`${fmt(t)} °C`:null,rh!=null?`${fmt(rh,0)} % RH`:null,v!=null?`${fmt(v,2)} kPa`:null].filter(Boolean).join(' · ')}
  function desktopCard(room){const s=sensor(room);return `<article class="panel"><div class="panel-title"><div><small>${esc(room.kind||'GROWBOX')}</small><h3>${esc(room.name)}</h3></div><span class="counter">${room.plant_count||0} Pfl. · ${room.device_count||0} Geräte</span></div><div class="system-grid"><div class="system-item"><span>Temperatur</span><b>${s.temperature_c!=null?`${fmt(s.temperature_c)} °C`:'—'}</b></div><div class="system-item"><span>Feuchte</span><b>${s.humidity_percent!=null?`${fmt(s.humidity_percent,0)} %`:'—'}</b></div><div class="system-item"><span>VPD</span><b>${s.vpd_kpa!=null?`${fmt(s.vpd_kpa,2)} kPa`:'—'}</b></div></div><p class="empty">${esc(room.description||room.light_cycle||'Keine zusätzliche Beschreibung.')}</p></article>`}
  function desktopSummary(room){return `<div class="device-row"><div><strong>${esc(room.name)}</strong><small>${esc(status(room)||`${room.plant_count||0} Pflanzen · ${room.device_count||0} Geräte`)}</small></div><span class="state-badge">${room.latest_sensor?'LIVE':'BEREIT'}</span></div>`}
  function mobileCard(room){const s=sensor(room);return `<article class="mcard"><header><div><small>${esc(room.kind||'GROWBOX')}</small><h2>${esc(room.name)}</h2></div><b>${room.plant_count||0} Pfl.</b></header><div class="mkv"><span>Temperatur</span><b>${s.temperature_c!=null?`${fmt(s.temperature_c)} °C`:'—'}</b><span>Luftfeuchte</span><b>${s.humidity_percent!=null?`${fmt(s.humidity_percent,0)} %`:'—'}</b><span>VPD</span><b>${s.vpd_kpa!=null?`${fmt(s.vpd_kpa,2)} kPa`:'—'}</b><span>Geräte</span><b>${room.device_count||0}</b></div></article>`}
  function applyPrimary(room){if(!room)return;const s=sensor(room);const map=[['temp','mTemp',s.temperature_c,1],['rh','mRh',s.humidity_percent,0],['vpd','mVpd',s.vpd_kpa,2]];for(const [desktop,mobile,value,digits] of map){if(value==null)continue;const a=document.getElementById(desktop);const b=document.getElementById(mobile);if(a)a.textContent=fmt(value,digits);if(b)b.textContent=fmt(value,digits)} }
  async function load(){try{const data=await api('/api/v1/rooms');const rooms=data.rooms||[];const summary=document.getElementById('growSummary');const cards=document.getElementById('growCards');const msummary=document.getElementById('mGrowSummary');const mcards=document.getElementById('mGrowCards');const select=document.getElementById('growSelector');if(summary)summary.innerHTML=rooms.length?rooms.slice(0,4).map(desktopSummary).join(''):'<div class="empty">Noch keine Growbox angelegt.</div>';if(cards)cards.innerHTML=rooms.length?rooms.map(desktopCard).join(''):'<article class="panel empty-state"><b>Noch keine Growbox-Konfiguration</b><p>Lege eine Growbox in der Raumverwaltung an.</p></article>';if(msummary)msummary.innerHTML=rooms.length?rooms.slice(0,3).map(r=>`<div class="mrow"><div><strong>${esc(r.name)}</strong><small>${esc(status(r)||`${r.plant_count||0} Pflanzen · ${r.device_count||0} Geräte`)}</small></div><span class="mbadge">${r.latest_sensor?'LIVE':'BEREIT'}</span></div>`).join(''):'<div class="mempty">Noch keine Growbox angelegt.</div>';if(mcards)mcards.innerHTML=rooms.length?rooms.map(mobileCard).join(''):'<article class="mcard"><b>Noch keine Growbox-Konfiguration</b><p class="muted">Lege zuerst eine Growbox an.</p></article>';if(select){const current=select.value;select.innerHTML='<option value="">Alle Growboxen</option>'+rooms.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current}applyPrimary(rooms[0]);}catch(_){}}
  load();setInterval(load,60000);
})();